import Link from "next/link";
import { getCoopiaAnalytics, type CoopiaPeriod } from "../../../lib/data/coopia-analytics";
import { getCoopiaAnalyticsSummary } from "../../../lib/coopia/analytics-summary";

export const dynamic = "force-dynamic";
const periods: Array<{ value: CoopiaPeriod; label: string }> = [{ value: "today", label: "Hoy" }, { value: "7d", label: "7 días" }, { value: "30d", label: "30 días" }];
function metric(value: number | null) { return value === null ? "Dato todavía no disponible" : value; }
function label(value: string) { return value.replaceAll("_", " "); }

export default async function CoopiaAdminPage({ searchParams }: { searchParams: Promise<{ period?: string }> }) {
  const params = await searchParams; const period = periods.some((item) => item.value === params.period) ? params.period as CoopiaPeriod : "7d";
  const data = await getCoopiaAnalytics(period); const summary = await getCoopiaAnalyticsSummary(data);
  const cards = [["Sesiones aproximadas", data.totals.sessions], ["Consultas", data.totals.messages], ["Derivaciones humanas", data.totals.handoffs], ["Consultas sin resolver", data.totals.unresolved], ["Feedback positivo", data.totals.feedbackPositive], ["Solicitudes comerciales", data.commercialRequests]] as const;
  return <section className="admin-page coopia-admin-page"><header className="admin-page-header"><div><span className="eyebrow">Analítica privada</span><h1>COOPIA</h1><p>Indicadores agregados y anónimos de atención. No se guardan conversaciones completas ni datos personales.</p></div></header>
    <nav className="admin-periods" aria-label="Período de analítica">{periods.map((item) => <Link key={item.value} className={item.value === period ? "active" : ""} href={`/admin/coopia?period=${item.value}`}>{item.label}</Link>)}</nav>
    {!data.available ? <div className="admin-empty-state"><strong>Fuente no disponible</strong><p>No pudimos consultar la analítica de COOPIA. Reintentá más tarde; no se muestran ceros como si fueran datos reales.</p></div> : <>
      {!data.eventSourceComplete && <div className="admin-empty-state"><strong>Datos insuficientes para una lectura completa</strong><p>El período supera el límite seguro de lectura agregada. No se calculan comparaciones ni conclusiones parciales.</p></div>}
      <section className="coopia-summary admin-card"><span className="eyebrow">{summary.source === "ai" ? "Resumen IA sobre agregados" : "Resumen determinístico"}</span><h2>Lectura operativa de COOPIA</h2><p>{summary.summary}</p>{summary.insights.length ? <ul>{summary.insights.map((item) => <li key={item}>{item}</li>)}</ul> : null}{summary.recommendations.length ? <ul>{summary.recommendations.map((item) => <li key={item}>{item}</li>)}</ul> : null}<small>Se procesa únicamente información agregada; no se envían conversaciones ni datos personales.</small></section>
      <section className="admin-metrics">{cards.map(([item, value]) => <article key={item}><small>{item}</small><strong>{metric(value)}</strong></article>)}<article><small>Resolution Rate</small><strong>{data.resolution.rate === null ? "Datos insuficientes" : `${data.resolution.rate}%`}</strong><span>{data.resolution.label}</span></article></section>
      <section className="coopia-admin-grid"><article className="admin-card"><h2>Funnel de COOPIA</h2><ol>{data.funnel.map((item) => <li key={item.id}><span>{item.label}{item.rateFromPrevious === null ? "" : ` · ${item.rateFromPrevious}%`}</span><b>{item.count}</b></li>)}</ol></article><article className="admin-card"><h2>COOPIA necesita aprender</h2>{data.needsLearning.length ? <ol>{data.needsLearning.map((item) => <li key={`${item.kind}-${item.label}`}><span>{item.kind === "intent" ? "Tema: " : "Servicio: "}{label(item.label)}</span><b>{item.count}</b></li>)}</ol> : <p>Dato todavía no disponible: no hay desenlaces agregados suficientes para priorizar mejoras.</p>}</article><article className="admin-card"><h2>COOPIA Pulse</h2>{data.pulse.length ? <ul>{data.pulse.map((item) => <li key={item.label}><strong>{item.label}</strong><br /><small>{item.detail}</small></li>)}</ul> : <p>No hay aumentos estadísticamente comparables para destacar.</p>}</article></section>
      <section className="coopia-admin-grid"><article className="admin-card"><h2>Temas principales</h2>{data.intents.length ? <ol>{data.intents.map((item) => <li key={item.label}><span>{label(item.label)}</span><b>{item.count}</b></li>)}</ol> : <p>Dato todavía no disponible para este período.</p>}</article><article className="admin-card"><h2>Servicios consultados</h2>{data.services.length ? <ol>{data.services.map((item) => <li key={item.label}><span>{label(item.label)}</span><b>{item.count}</b></li>)}</ol> : <p>Dato todavía no disponible para este período.</p>}</article><article className="admin-card"><h2>Comparación de períodos</h2><ol>{data.trends.map((item) => <li key={item.id}><span>{item.label}{item.status === "comparable" ? ` · ${item.changePercent! > 0 ? "+" : ""}${item.changePercent}%` : " · Sin período comparable"}</span><b>{item.current}</b></li>)}</ol></article></section>
      <section className="admin-card"><h2>Actividad reciente</h2>{data.recent.length ? <ul className="coopia-recent">{data.recent.map((item, index) => <li key={`${item.at}-${index}`}><span>{item.event}</span><small>{new Intl.DateTimeFormat("es-AR", { dateStyle: "short", timeStyle: "short" }).format(new Date(item.at))}</small></li>)}</ul> : <p>No hay actividad registrada para el período seleccionado.</p>}</section>
    </>}
  </section>;
}
