"use client";

import { FormEvent, useEffect, useState } from "react";
import type { AssistantResult } from "../../lib/ai/results";
import { useNavigationContext } from "./navigation-context";
import { ServiceRequestForm } from "./service-request-form";
import { HumanHandoffCard } from "./human-handoff-card";

type Plan = { id: string; name: string; technology: string | null; speed_down_mbps: number | null; price_amount: number | null; currency: string | null };
type Coverage = { coverageStatus: "available" | "nearby" | "planned" | "unavailable" | "unknown"; message: string; commercialAvailability: boolean; plans: Plan[]; nextAction: string };

function track(journeyId: string, sessionId: string, eventType: string, action?: string, result?: string, metadata?: { routingWindow: "office_hours" | "after_hours"; contactPurpose: string }) { if (journeyId && sessionId) void fetch("/api/journey/events", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ journeyId, sessionId, eventType, action, result, metadata, page: `${location.pathname}${location.hash}` }) }); }
function ActionLink({ action, complaintRoute, service }: { action: AssistantResult["actions"][number]; complaintRoute?: AssistantResult["complaintRoute"]; service?: AssistantResult["service"] }) { const nav = useNavigationContext(); if (!action.href) return null; return <a className="assistant-action" href={action.href} onClick={() => { nav.recordAction(action.id); const complaint = action.id === "OPEN_COMPLAINT_WHATSAPP"; track(nav.journeyId, nav.sessionId, complaint ? "complaint_whatsapp_opened" : action.id === "OPEN_WHATSAPP" ? "whatsapp_opened" : "action_clicked", action.id, service, complaint && complaintRoute ? { routingWindow: complaintRoute.routingWindow, contactPurpose: complaintRoute.contactPurpose } : undefined); }}>{action.label} <span>→</span></a>; }

function FiberCoverageCard({ result }: { result: AssistantResult }) {
  const nav = useNavigationContext(); const [street, setStreet] = useState(""); const [number, setNumber] = useState(""); const [coverage, setCoverage] = useState<Coverage | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setLoading(true); track(nav.journeyId, nav.sessionId, "form_started", "CHECK_COVERAGE"); try { const response = await fetch("/api/coverage-check", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ street, number, journeyId: nav.journeyId, sessionId: nav.sessionId }) }); const data = await response.json() as Coverage & { error?: string }; if (!response.ok) throw new Error(data.error || "No pudimos consultar la cobertura."); setCoverage(data); if (data.plans.length) track(nav.journeyId, nav.sessionId, "internet_plans_viewed", undefined, data.coverageStatus); track(nav.journeyId, nav.sessionId, "form_completed", "CHECK_COVERAGE", data.coverageStatus); } catch (cause) { setError(cause instanceof Error ? cause.message : "No pudimos consultar la cobertura."); } finally { setLoading(false); } }
  const action = coverage?.nextAction === "fiber_waitlist" ? "Solicitar aviso de cobertura" : coverage?.nextAction === "coverage_validation" ? "Solicitar validación técnica" : "Continuar con la solicitud";
  return <section className="assistant-card coverage-card"><header><small>Internet y fibra</small><h3>Consultemos tu domicilio</h3><p>La disponibilidad final requiere validación técnica.</p></header>{!coverage ? <form onSubmit={submit}><label>Calle<input value={street} minLength={3} required onChange={(event) => setStreet(event.target.value)} placeholder="Ej.: San Martín" /></label><label>Altura<input value={number} required inputMode="numeric" onChange={(event) => setNumber(event.target.value.replace(/\D/g, "").slice(0, 6))} placeholder="Ej.: 1250" /></label><button disabled={loading}>{loading ? "Consultando…" : "Consultar cobertura"}</button>{error && <p role="alert" className="form-error">{error}</p>}</form> : <div className={`assistant-result ${coverage.coverageStatus}`}><small>{coverage.commercialAvailability ? "Planes publicados para tu domicilio" : "Revisión necesaria"}</small><h4>{coverage.commercialAvailability ? "Servicio disponible" : "Sin cobertura confirmada"}</h4><p>{coverage.message}</p>{coverage.plans.map((plan) => <div className="assistant-plan" key={plan.id}><strong>{plan.name}</strong>{plan.technology && <span>{plan.technology}</span>}{plan.speed_down_mbps && <span>{plan.speed_down_mbps} Mbps</span>}{plan.price_amount !== null && <span>{new Intl.NumberFormat("es-AR", { style: "currency", currency: plan.currency || "ARS", maximumFractionDigits: 0 }).format(plan.price_amount)}</span>}</div>)}<div><button onClick={() => setCoverage(null)}>Modificar domicilio</button><a href="#contratar" onClick={() => { track(nav.journeyId, nav.sessionId, coverage.nextAction === "fiber_waitlist" ? "fiber_waitlist_started" : "navigation_executed", "REQUEST_INSTALLATION"); document.querySelector("#contratar")?.scrollIntoView({ behavior: "smooth" }); }}>{action} →</a></div></div>}<div className="assistant-card-actions">{result.actions.map((action) => <ActionLink action={action} complaintRoute={result.complaintRoute} service={result.service} key={action.id} />)}</div></section>;
}

function SimpleCard({ result }: { result: AssistantResult }) { const incident = ["outage", "partial", "maintenance"].includes(String(result.ui?.data.status)); const payment = result.ui?.type === "payment"; return <section className={`assistant-card ${payment ? "payment-card" : "status-card"}`}><div className="assistant-status-icon">{payment ? "$" : incident ? "!" : "i"}</div><div><small>{payment ? "Facturas y pagos" : `Estado de ${String(result.ui?.data.service || "servicio")}`}</small><h3>{payment ? "Resolvé tu factura en línea" : incident ? "Incidencia informada" : "Sin incidencia general confirmada"}</h3><p>{result.message}</p><div className="assistant-card-actions">{result.actions.map((action) => <ActionLink action={action} complaintRoute={result.complaintRoute} service={result.service} key={action.id} />)}</div></div></section>; }
function ComplaintServicePicker({ onSelect }: { onSelect: (service: string) => void }) { return <section className="assistant-card"><small>Reclamos</small><h3>Elegí el servicio</h3><div className="assistant-card-actions">{["Energía", "Internet/Fibra", "Telefonía", "Sepelio"].map((service) => <button type="button" className="assistant-action" key={service} onClick={() => onSelect(service)}>{service}</button>)}</div></section>; }
export function AssistantUIRenderer({ result, onComplaintServiceSelect }: { result: AssistantResult; onComplaintServiceSelect?: (service: string) => void }) { const nav = useNavigationContext(); useEffect(() => { track(nav.journeyId, nav.sessionId, "contextual_component_rendered", result.ui?.type, result.intent); }, [nav.journeyId, nav.sessionId, result.intent, result.ui?.type]); if (result.ui?.type === "fiber_coverage" || result.ui?.type === "internet_plans") return <FiberCoverageCard result={result} />; if (result.ui?.type === "service_request_form") return <ServiceRequestForm requestType={String(result.ui.data.requestType || "")} />; if (result.ui?.type === "human_handoff") return <HumanHandoffCard />; if (result.ui?.type === "complaint_service_picker" && onComplaintServiceSelect) return <ComplaintServicePicker onSelect={onComplaintServiceSelect} />; if (result.ui?.type === "service_status" || result.ui?.type === "payment") return <SimpleCard result={result} />; return null; }
export function ContextualQuickActions() { const nav = useNavigationContext(); if (!nav.intent || nav.recommendedActions.length === 0) return null; return <nav className="contextual-actions" aria-label="Acciones recomendadas"><strong>Acciones para tu consulta</strong><div>{nav.recommendedActions.map((action) => <ActionLink action={action} key={action.id} />)}</div></nav>; }
