"use client";
import { FormEvent, useEffect, useState } from "react";
import type { AssistantResult } from "../../lib/ai/results";
import { useNavigationContext } from "./navigation-context";
type Coverage = { status: string; message: string; service?: { planName: string; technology: string; speedMbps: number | null } | null };
function track(journeyId: string, sessionId: string, eventType: string, action?: string, result?: string) { if (journeyId && sessionId) void fetch("/api/journey/events", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ journeyId, sessionId, eventType, action, result, page: `${location.pathname}${location.hash}` }) }); }
function ActionLink({ action }: { action: AssistantResult["actions"][number] }) { const nav = useNavigationContext(); if (!action.href) return null; return <a className="assistant-action" href={action.href} onClick={() => { nav.recordAction(action.id); track(nav.journeyId, nav.sessionId, action.id === "OPEN_WHATSAPP" ? "whatsapp_opened" : "action_clicked", action.id); }}>{action.label} <span>→</span></a>; }
function FiberCoverageCard({ result }: { result: AssistantResult }) { const nav = useNavigationContext(); const [street, setStreet] = useState(""); const [number, setNumber] = useState(""); const [coverage, setCoverage] = useState<Coverage | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); setError(""); setLoading(true); track(nav.journeyId, nav.sessionId, "form_started", "CHECK_COVERAGE"); try { const response = await fetch("/api/coverage-check", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ street, number }) }); const data = await response.json() as Coverage & { error?: string }; if (!response.ok && data.status !== "configuration_pending") throw new Error(data.error || "No pudimos consultar la cobertura."); setCoverage(data); track(nav.journeyId, nav.sessionId, "form_completed", "CHECK_COVERAGE", data.status); } catch (cause) { setError(cause instanceof Error ? cause.message : "No pudimos consultar la cobertura."); } finally { setLoading(false); } } return <section className="assistant-card coverage-card"><header><small>Internet y fibra</small><h3>Consultemos tu domicilio</h3><p>La disponibilidad final requiere validación técnica.</p></header>{!coverage ? <form onSubmit={submit}><label>Calle<input value={street} minLength={3} required onChange={(event) => setStreet(event.target.value)} placeholder="Ej.: San Martín" /></label><label>Altura<input value={number} required inputMode="numeric" onChange={(event) => setNumber(event.target.value.replace(/\D/g, "").slice(0, 6))} placeholder="Ej.: 1250" /></label><button disabled={loading}>{loading ? "Consultando…" : "Consultar cobertura"}</button>{error && <p role="alert" className="form-error">{error}</p>}</form> : <div className={`assistant-result ${coverage.status}`}><small>{coverage.service ? "Servicio encontrado" : "Revisión necesaria"}</small><h4>{coverage.service?.planName || "Sin cobertura confirmada"}</h4>{coverage.service && <p>{coverage.service.technology}{coverage.service.speedMbps ? ` · ${coverage.service.speedMbps} Mbps` : ""}</p>}<p>{coverage.message}</p><div><button onClick={() => setCoverage(null)}>Modificar domicilio</button><a href="#contratar" onClick={() => { track(nav.journeyId, nav.sessionId, "navigation_executed", "REQUEST_INSTALLATION"); document.querySelector("#contratar")?.scrollIntoView({ behavior: "smooth" }); }}>Solicitar instalación →</a></div></div>}<div className="assistant-card-actions">{result.actions.map((action) => <ActionLink action={action} key={action.id} />)}</div></section>; }
function SimpleCard({ result }: { result: AssistantResult }) { const incident = result.ui?.data.status === "incident"; const payment = result.ui?.type === "payment"; return <section className={`assistant-card ${payment ? "payment-card" : "status-card"}`}><div className="assistant-status-icon">{payment ? "$" : incident ? "!" : "i"}</div><div><small>{payment ? "Facturas y pagos" : `Estado de ${String(result.ui?.data.service || "servicio")}`}</small><h3>{payment ? "Resolvé tu factura en línea" : incident ? "Incidencia informada" : "Sin incidencia general confirmada"}</h3><p>{result.message}</p><div className="assistant-card-actions">{result.actions.map((action) => <ActionLink action={action} key={action.id} />)}</div></div></section>; }
export function AssistantUIRenderer({ result }: { result: AssistantResult }) { const nav = useNavigationContext(); useEffect(() => { track(nav.journeyId, nav.sessionId, "contextual_component_rendered", result.ui?.type, result.intent); }, [nav.journeyId, nav.sessionId, result.intent, result.ui?.type]); if (result.ui?.type === "fiber_coverage") return <FiberCoverageCard result={result} />; if (result.ui?.type === "service_status" || result.ui?.type === "payment") return <SimpleCard result={result} />; return null; }
export function ContextualQuickActions() { const nav = useNavigationContext(); if (!nav.intent || nav.recommendedActions.length === 0) return null; return <nav className="contextual-actions" aria-label="Acciones recomendadas"><strong>Acciones para tu consulta</strong><div>{nav.recommendedActions.map((action) => <ActionLink action={action} key={action.id} />)}</div></nav>; }
