"use client";

import { FormEvent, useRef, useState } from "react";
import Link from "next/link";
import { AssistantUIRenderer } from "./assistant-ui";
import { useCoopia } from "./coopia-context";
import { coopiaActiveContext, coopiaInitialNeeds, coopiaLoadingCopy, coopiaMoreNeeds } from "../../lib/coopia/interaction-flow";

function RichText({ content }: { content: string }) { return <div className="message-content">{content.trim().split(/\n\s*\n/).filter(Boolean).map((block, index) => <p key={index}>{block}</p>)}</div>; }

export function CoopiaConversation({ compact = false, home = false }: { compact?: boolean; home?: boolean }) {
  const coopia = useCoopia(); const inputRef = useRef<HTMLTextAreaElement>(null); const [showMore, setShowMore] = useState(false); const [showHistory, setShowHistory] = useState(false); const [hideLimited, setHideLimited] = useState(false); const [feedbackFor, setFeedbackFor] = useState<string | null>(null);
  const hasHistory = coopia.messages.length > 0; const hasStructuredStep = Boolean(coopia.assistantResult); const needs = coopiaInitialNeeds(coopia.pageContext); const moreNeeds = coopiaMoreNeeds(coopia.pageContext); const currentAssistantText = [...coopia.messages].reverse().find((message) => message.role === "assistant" && message.content)?.content || "";
  const ask = (prompt: string) => { setShowMore(false); void coopia.ask(prompt); }; const submit = (event: FormEvent) => { event.preventDefault(); void coopia.ask(coopia.input); }; const changeNeed = () => { coopia.clearActiveStep(); inputRef.current?.focus(); };
  return <div className={`coopia-conversation coopia-guided ${compact ? "coopia-compact" : ""} ${home ? "coopia-home" : ""}`}>
    {hasStructuredStep ? <section className="coopia-active-step" aria-label="Paso actual"><div className="coopia-step-context"><strong>{coopiaActiveContext(coopia.assistantResult)}</strong><button type="button" onClick={changeNeed}>Cambiar</button></div><AssistantUIRenderer result={coopia.assistantResult!} resultKey={coopia.assistantResultKey} onComplaintServiceSelect={(service) => ask(`Quiero hacer un reclamo de ${service}`)} /></section> : <section className="coopia-start">{!compact && <><div className="coopia-avatar" aria-hidden="true">✦</div><small>COOPIA</small></>}{home && <p className="coopia-home-kicker">Asistente de COOPSAR</p>}<h2>¿Qué necesitás resolver?</h2><div className="coopia-needs" aria-label="Necesidades frecuentes">{needs.map((item) => <button type="button" key={item.prompt} onClick={() => ask(item.prompt)}>{item.label}<span>→</span></button>)}</div><button type="button" className="coopia-more-toggle" aria-expanded={showMore} onClick={() => setShowMore((value) => !value)}>{showMore ? "Ver menos opciones" : "Ver más opciones"}</button>{showMore && <div className="coopia-more-needs">{moreNeeds.map((item) => <button type="button" key={item.prompt} onClick={() => ask(item.prompt)}>{item.label}</button>)}</div>}</section>}
    {coopia.loading && <div className="coopia-loading" role="status"><i /><span>{coopiaLoadingCopy(coopia.input || coopia.messages.at(-1)?.content || "")}</span></div>}
    {coopia.error && <div className="coopia-error" role="alert"><strong>No pude completar ese paso.</strong><span>Podés intentarlo otra vez o seguir por atención personal.</span><button type="button" onClick={() => void coopia.ask(coopia.messages.at(-1)?.content || coopia.input)}>Reintentar</button></div>}
    {coopia.aiLimited && !hideLimited && <div className="coopia-availability"><span>Podés seguir resolviendo pagos, cobertura, servicios y trámites.</span><button type="button" onClick={() => setHideLimited(true)} aria-label="Ocultar aviso">×</button></div>}
    {hasHistory && <section className="coopia-history"><button type="button" className="coopia-history-toggle" aria-expanded={showHistory} onClick={() => setShowHistory((value) => !value)}>{showHistory ? "Ocultar conversación" : "Ver conversación"}</button>{showHistory && <div className="chat-log" aria-live="polite">{coopia.messages.map((message, index) => <div className={`message ${message.role}`} key={`${message.role}-${index}`}><small>{message.role === "user" ? "Vos" : "COOPIA"}</small>{message.content ? <RichText content={message.content} /> : <p>…</p>}</div>)}{currentAssistantText && feedbackFor !== currentAssistantText && !coopia.loading && <div className="coopia-feedback"><span>¿Te sirvió esta respuesta?</span><button type="button" onClick={() => { coopia.feedback(true); setFeedbackFor(currentAssistantText); }}>Sí</button><button type="button" onClick={() => { coopia.feedback(false); setFeedbackFor(currentAssistantText); }}>No</button></div>}</div>}</section>}
    <form className="chat-input" onSubmit={submit}><label className="sr-only" htmlFor={compact ? "coopia-global-query" : "assistant-query"}>Contanos qué necesitás</label><textarea ref={inputRef} id={compact ? "coopia-global-query" : "assistant-query"} value={coopia.input} maxLength={1200} onChange={(event) => coopia.setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }} placeholder="Contame qué necesitás..." rows={compact ? 2 : home ? 1 : 3} /><button disabled={!coopia.input.trim() || coopia.loading} aria-label="Enviar consulta" title="Enviar consulta"><span className="coopia-send-label">Enviar</span><span aria-hidden="true">↑</span></button></form>
    <div className="coopia-human"><a href={coopia.handoffUrl} onClick={() => coopia.track("coopia_handoff", undefined, "whatsapp")}>Hablar con una persona <span>→</span></a>{!hasStructuredStep && <Link href="/tramites">Ver trámites</Link>}</div><div className="ai-legal"><span>La IA puede cometer errores. No compartas contraseñas, datos bancarios ni información sensible.</span><Link href="/privacidad">Privacidad</Link></div>
  </div>;
}
