"use client";

import { useEffect, useMemo, useState } from "react";

type Candidate = { id: string; entityType: string; title: string; status: string; provenanceCount: number; validationPending: boolean };
type Proposal = { id: string; entity_type: string; entity_id: string; status: string; risk_level: string; validation_flags: string[]; updated_at: string };
const labels: Record<string, string> = { service: "Servicio", help_article: "Artículo", faq: "FAQ", internet_plan: "Plan", contact_channel: "Contacto" };

export default function EditorialContentPage() {
  const [candidates, setCandidates] = useState<Candidate[]>([]); const [proposals, setProposals] = useState<Proposal[]>([]); const [filter, setFilter] = useState("all"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState<string | null>(null);
  const load = async () => { const response = await fetch("/api/admin/editorial-proposals", { cache: "no-store" }); const data = await response.json() as { candidates?: Candidate[]; proposals?: Proposal[]; error?: string }; if (!response.ok) setMessage(data.error || "No pudimos cargar el centro de contenidos."); else { setCandidates(data.candidates || []); setProposals(data.proposals || []); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const filtered = useMemo(() => candidates.filter((candidate) => filter === "all" || candidate.entityType === filter), [candidates, filter]);
  const proposalByCandidate = new Map(proposals.map((proposal) => [proposal.entity_id, proposal]));
  const generate = async (candidate: Candidate) => { setBusy(candidate.id); setMessage(""); try { const response = await fetch("/api/admin/editorial-proposals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ entityType: candidate.entityType, entityId: candidate.id }) }); const data = await response.json() as { error?: string }; setMessage(response.ok ? "Propuesta guardada para revisión humana." : data.error || "No pudimos generar la propuesta."); if (response.ok) await load(); } finally { setBusy(null); } };
  const generateBatch = async () => { setBusy("batch"); setMessage(""); try { const response = await fetch("/api/admin/editorial-proposals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ batchLimit: 10 }) }); const data = await response.json() as { error?: string; processed?: number; created?: number; reused?: number }; setMessage(response.ok ? `Lote procesado: ${data.created || 0} propuesta(s) nueva(s), ${data.reused || 0} existente(s).` : data.error || "No pudimos generar el lote."); if (response.ok) await load(); } finally { setBusy(null); } };
  return <section className="admin-page"><header className="admin-page-header"><div><span className="eyebrow">Centro de contenidos</span><h1>Curaduría editorial IA</h1><p>COOPIA propone mejoras sobre borradores. Ninguna propuesta modifica ni publica contenido sin revisión humana.</p></div><button className="primary" disabled={busy === "batch"} onClick={() => void generateBatch()}>{busy === "batch" ? "Procesando lote…" : "Generar lote de 10"}</button></header><div className="admin-card"><label>Filtrar contenido<select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">Todo el contenido</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>{message && <p className="admin-message" role="status">{message}</p>}<div className="admin-card admin-table-wrap"><table><thead><tr><th>Contenido</th><th>Tipo</th><th>Estado</th><th>Provenance</th><th>Propuesta</th><th /></tr></thead><tbody>{filtered.map((candidate) => { const proposal = proposalByCandidate.get(candidate.id); return <tr key={candidate.id}><td>{candidate.title}</td><td>{labels[candidate.entityType] || candidate.entityType}</td><td><span className={`admin-status ${candidate.status}`}>{candidate.status}</span></td><td>{candidate.provenanceCount ? `${candidate.provenanceCount} fuente(s)` : "Sin provenance"}</td><td>{proposal ? `${proposal.status}${proposal.validation_flags.length ? " · validar" : ""}` : "Pendiente"}</td><td><button className="primary" disabled={busy === candidate.id || candidate.status !== "draft"} onClick={() => void generate(candidate)}>{busy === candidate.id ? "Generando…" : proposal ? "Regenerar" : "Generar propuesta"}</button></td></tr>; })}</tbody></table>{filtered.length === 0 && <p>No hay borradores disponibles para curar.</p>}</div><aside className="admin-card"><h2>Reglas de seguridad</h2><p>Precios, contactos, horarios, direcciones, cobertura y contenido legal requieren validación. Los contenidos publicados nunca son reemplazados automáticamente.</p></aside></section>;
}
