"use client";

import { useEffect, useState } from "react";
import { funeralRequestStatuses, funeralStatusLabel, type FuneralRequestStatus } from "../../../../lib/funeral-family-update";

type ListRow = { id: string; requestNumber: string; memberNumber: string; holderName: string; dni: string; phone: string; status: FuneralRequestStatus; createdAt: string };
type Detail = { request: { id: string; request_number: string; member_number: string; holder_full_name: string; holder_dni: string; phone: string; email: string | null; status: FuneralRequestStatus; consent: boolean; created_at: string }; members: Array<{ id: string; full_name: string; dni: string; birth_date: string; relationship: string }>; audit: Array<{ id: string; action: string; old_status: string | null; new_status: string | null; actor_email: string | null; created_at: string }> };

export function FuneralFamilyInbox() {
  const [rows, setRows] = useState<ListRow[]>([]), [selected, setSelected] = useState<Detail | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
  async function load() { setLoading(true); const response = await fetch("/api/admin/sepelio/planillas", { cache: "no-store" }); const data = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) { setError(data.error || "No pudimos cargar las solicitudes."); return; } setRows(data.requests || []); }
  useEffect(() => { let active = true; void fetch("/api/admin/sepelio/planillas", { cache: "no-store" }).then(async (response) => ({ response, data: await response.json().catch(() => ({})) })).then(({ response, data }) => { if (!active) return; setLoading(false); if (!response.ok) { setError(data.error || "No pudimos cargar las solicitudes."); return; } setRows(data.requests || []); }).catch(() => { if (active) { setLoading(false); setError("No pudimos cargar las solicitudes."); } }); return () => { active = false; }; }, []);
  async function open(id: string) { const response = await fetch(`/api/admin/sepelio/planillas?id=${encodeURIComponent(id)}`, { cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(data.error || "No pudimos cargar el detalle."); return; } setSelected(data); }
  async function update(status: FuneralRequestStatus) { if (!selected) return; setSaving(true); const response = await fetch("/api/admin/sepelio/planillas", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: selected.request.id, status }) }); const data = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) { setError(data.error || "No pudimos actualizar la solicitud."); return; } setSelected((current) => current ? { ...current, request: { ...current.request, status } } : current); void load(); }
  return <section className="admin-content funeral-admin"><p className="eyebrow">Sepelio</p><h1>Actualizaciones de grupo familiar</h1><p className="admin-intro">Solicitudes privadas. Los datos completos sólo se muestran al abrir un caso.</p>{error && <p className="admin-error" role="alert">{error}</p>}<div className="funeral-admin-layout"><div className="funeral-admin-list"><h2>Solicitudes recientes</h2>{loading ? <p>Cargando solicitudes…</p> : rows.length === 0 ? <p>No hay solicitudes registradas.</p> : <ul>{rows.map((row) => <li key={row.id}><button type="button" onClick={() => void open(row.id)}><span><strong>{row.requestNumber}</strong><small>{row.holderName} · DNI {row.dni} · Tel. {row.phone}</small></span><em>{funeralStatusLabel(row.status)}</em></button></li>)}</ul>}</div><aside className="funeral-admin-detail" aria-live="polite">{!selected ? <p>Seleccioná una solicitud para ver el detalle.</p> : <><p className="eyebrow">{selected.request.request_number}</p><h2>{selected.request.holder_full_name}</h2><dl><div><dt>DNI</dt><dd>{selected.request.holder_dni}</dd></div><div><dt>Teléfono</dt><dd>{selected.request.phone}</dd></div><div><dt>Correo</dt><dd>{selected.request.email || "No informado"}</dd></div><div><dt>Referencia</dt><dd>{selected.request.member_number}</dd></div></dl><h3>Integrantes</h3><ul>{selected.members.map((member) => <li key={member.id}>{member.full_name} · {member.relationship} · DNI {member.dni}</li>)}</ul><label>Estado<select value={selected.request.status} disabled={saving} onChange={(event) => void update(event.target.value as FuneralRequestStatus)}>{funeralRequestStatuses.map((status) => <option key={status} value={status}>{funeralStatusLabel(status)}</option>)}</select></label><h3>Auditoría</h3><ul>{selected.audit.map((item) => <li key={item.id}>{item.action === "status_changed" ? `${item.old_status || "—"} → ${item.new_status}` : "Solicitud creada"} · {new Date(item.created_at).toLocaleString("es-AR")}</li>)}</ul></>}</aside></div></section>;
}
