import Link from "next/link";
export const news=[
 {slug:"mantenimiento-infraestructura-electrica",category:"ENERGÍA",date:"1 JUL 2026",title:"Mantenimiento y mejoras en la infraestructura eléctrica",excerpt:"Continúan los trabajos preventivos y las mejoras de capacidad en distintos sectores de Sarmiento.",body:["COOPSAR continúa ejecutando tareas preventivas y mejoras sobre la red de distribución eléctrica.","Los trabajos permiten renovar componentes, mejorar la capacidad de transformación y reforzar la calidad del servicio.","Cuando una intervención requiera interrumpir el suministro, la información oficial indicará fecha, horario y zonas alcanzadas."]},
 {slug:"fibra-optica-nuevas-zonas",category:"FIBRA ÓPTICA",date:"9 JUL 2026",title:"La fibra óptica continúa llegando a nuevas zonas",excerpt:"La red FTTH de COOPSAR sigue ampliándose para ofrecer mayor velocidad, estabilidad y capacidad.",body:["La expansión de la fibra óptica representa una inversión estratégica para Sarmiento.","La tecnología FTTH lleva la fibra directamente hasta el hogar o comercio.","La contratación está sujeta a disponibilidad técnica."]},
 {slug:"servicio-solidario-sepelios",category:"SEPELIO",date:"13 JUN 2026",title:"El Servicio Solidario de Sepelios acompaña a las familias",excerpt:"Un servicio cooperativo creado para brindar asistencia y contención.",body:["El Servicio Solidario forma parte del acompañamiento comunitario de COOPSAR.","Es importante mantener actualizada la planilla del grupo familiar.","Guardia: 297 624-1614 / 297 624-1615."]}
];
export function Header(){return <header><Link className="logo" href="/"><span>COOP</span>SAR<small>SERVICIOS PÚBLICOS</small></Link><nav><Link href="/energia">Energía</Link><Link href="/internet-telefonia">Internet y teléfono</Link><Link href="/fibra-optica">Fibra óptica</Link><Link href="/sepelio">Sepelio</Link><Link href="/noticias">Noticias</Link></nav><a className="portal" href="https://www.cooponlineweb.com.ar/SARMIENTO/Login" target="_blank">Oficina virtual →</a></header>}
export function NewsCards(){return <div className="news">{news.map((n,i)=><article className={i===0?"featured":""} key={n.slug}><div className="visual"><b>{n.category}</b></div><div><small>{n.date} · {n.category}</small><h3>{n.title}</h3><p>{n.excerpt}</p><Link href={"/noticias/"+n.slug}>Leer noticia →</Link></div></article>)}</div>}
export function Contact(){return <section className="contact"><div><small>¿NECESITÁS AYUDA?</small><h2>Estamos para acompañarte.</h2></div><a href="https://wa.me/5492975376656">◉ WhatsApp<br/><small>+54 9 2975 37-6656</small></a><a href="tel:+542974364961">⚡ Guardia de Energía<br/><small>297 436-4961</small></a></section>}
export function Footer(){return <footer><div><b>COOPSAR</b><p>Cooperativa de Provisión de Servicios Públicos de Sarmiento Ltda.</p></div><div><Link href="/energia">Energía</Link><Link href="/internet-telefonia">Internet y Telefonía</Link><Link href="/fibra-optica">Fibra óptica</Link><Link href="/sepelio">Sepelio</Link></div><div><Link href="/institucional">Institucional</Link><Link href="/estado-servicios">Estado de servicios</Link><Link href="/noticias">Noticias</Link><Link href="/contacto">Contacto</Link></div><div><p>Lunes a viernes · 8:00 a 15:00<br/>Roca 663 · Sarmiento, Chubut</p></div><small>© 2026 COOPSAR</small></footer>}
