"use client";

import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import { CONTACT } from "../lib/coopsar-data";
import type { NewsArticle } from "../lib/news";
const navigation = [["Inicio", "/"], ["Asistente", "/#asistente"], ["Energía", "/energia"], ["Internet y fibra", "/internet"], ["Telefonía", "/telefonia"], ["Sepelio", "/sepelio"], ["Trámites", "/tramites"], ["Noticias", "/noticias"], ["Institucional", "/institucional"], ["Contacto", "/contacto"]];

export function Brand() { return <Link className="brand" href="/" aria-label="COOPSAR, inicio"><span className="brand-mark" aria-hidden="true"><i /><i /><i /></span><span className="brand-name">COOP<strong>SAR</strong><small>Servicios públicos</small></span></Link>; }
export function Header() { const [open, setOpen] = useState(false); return <header className="site-header"><Brand /><nav className="desktop-nav" aria-label="Navegación principal">{navigation.slice(1).map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</nav><a className="button button-dark header-action" href={CONTACT.virtualOffice} target="_blank" rel="noreferrer">Oficina virtual <span>↗</span></a><button className="menu-toggle" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu" aria-label="Abrir menú"><i /><i /><i /></button>{open && <div className="menu-backdrop" onClick={() => setOpen(false)} />}<nav id="mobile-menu" className={open ? "mobile-nav open" : "mobile-nav"} aria-label="Navegación móvil"><div><Brand /><button onClick={() => setOpen(false)} aria-label="Cerrar menú">×</button></div>{navigation.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)}>{label}<span>→</span></Link>)}<a className="button button-dark" href={CONTACT.virtualOffice}>Oficina Virtual ↗</a></nav></header>; }
export function NewsCards({ items }: { items: NewsArticle[] }) { return <div className="news-grid">{items.map((item, index) => <article className={`news-card news-card-${index + 1}`} key={item.id}>{item.imageUrl ? <div className="news-art news-photo"><Image src={item.imageUrl} alt="" fill sizes="(max-width: 800px) 100vw, 33vw" /></div> : <div className="news-art" aria-hidden="true"><span>{String(index + 1).padStart(2, "0")}</span></div>}<div className="news-copy"><small>{item.date} · {item.category}</small><h3>{item.title}</h3><p>{item.excerpt}</p><Link className="text-link" href={`/noticias/${item.slug}`}>Leer noticia ↗</Link></div></article>)}</div>; }
export function Contact() { return <section className="contact-band"><div><span className="eyebrow eyebrow-dark">Atención cercana</span><h2>Estamos para<br />acompañarte.</h2></div><a className="contact-item" href={`https://wa.me/${CONTACT.whatsapp}`}><span className="contact-icon">W</span><span><small>WhatsApp comercial</small><strong>{CONTACT.whatsappDisplay}</strong></span><b>↗</b></a><a className="contact-item" href={`tel:+542974364961`}><span className="contact-icon">24</span><span><small>Guardia de energía</small><strong>{CONTACT.energyGuard}</strong></span><b>↗</b></a></section>; }
export function Footer() { return <footer className="site-footer"><div className="footer-lead"><Brand /><p>Cooperativa de Provisión de Servicios Públicos de Sarmiento Ltda.</p></div><div><b>Servicios</b><Link href="/energia">Energía</Link><Link href="/internet">Internet y fibra</Link><Link href="/telefonia">Telefonía</Link><Link href="/sepelio">Sepelio</Link></div><div><b>Ayuda</b><Link href="/centro-de-ayuda">Centro de ayuda</Link><Link href="/tramites">Trámites</Link><Link href="/cortes-programados">Estado de servicios</Link><Link href="/privacidad">Privacidad</Link></div><div><b>Atención</b><p>{CONTACT.hours}</p><p>{CONTACT.office}</p></div><div className="footer-bottom"><small>© 2026 COOPSAR</small><small>Servicios esenciales, compromiso local.</small></div></footer>; }
