"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
type Contact = { id: string; service: string; channel_type: string; label: string; value: string; public_value: string; purpose: string; status: "draft" | "published" | "archived"; sort_order: number };
const empty = (): Contact => ({ id: "", service: "internet", channel_type: "whatsapp", label: "", value: "", public_value: "", purpose: "commercial", status: "draft", sort_order: 0 });
export default function AdminContactsPage() {
  const [contacts, setContacts] = useState<Contact[]>([]); const [editing, setEditing] = useState<Contact | null>(null); const [message, setMessage] = useState("");
  const load = async () => { const response = await fetch("/api/admin/configuracion/contactos", { cache: "no-store" }); const data = await response.json(); setContacts(data.contacts || []); if (!response.ok) setMessage(data.error || "No pudimos cargar los contactos."); }; useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); const payload = { id: editing.id || undefined, service: form.get("service"), channelType: form.get("channelType"), label: form.get("label"), value: form.get("value"), publicValue: form.get("publicValue"), purpose: form.get("purpose"), status: form.get("status"), sortOrder: Number(form.get("sortOrder")) || 0 }; const response = await fetch("/api/admin/configuracion/contactos", { method: editing.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) { setMessage(data.error || "No pudimos guardar el contacto."); return; } setEditing(null); setMessage("Canal guardado."); await load(); }
  return <main className="admin"><Link href="/admin">← Administración</Link><h1>Canales públicos de contacto</h1><p>Publicá solo información confirmada. No cargues secretos, contraseñas ni datos internos.</p>{message && <p role="status" className="admin-message">{message}</p>}{editing ? <form className="news-editor" onSubmit={save}><label>Servicio<select name="service" defaultValue={editing.service}>{["general", "internet", "energy", "funeral", "billing", "phone"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Tipo<select name="channelType" defaultValue={editing.channel_type}>{["phone", "whatsapp", "url", "address", "hours"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Etiqueta<input name="label" required defaultValue={editing.label} /></label><label>Valor interno de referencia<input name="value" required defaultValue={editing.value} /></label><label>Valor que verá el público<input name="publicValue" required defaultValue={editing.public_value} /></label><label>Propósito<input name="purpose" required defaultValue={editing.purpose} /></label><label>Orden<input name="sortOrder" type="number" min="0" defaultValue={editing.sort_order} /></label><label>Estado<select name="status" defaultValue={editing.status}><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label><button className="primary">Guardar</button><button type="button" onClick={() => setEditing(null)}>Cancelar</button></form> : <><button className="primary" onClick={() => setEditing(empty())}>Nuevo canal</button><table><thead><tr><th>Servicio</th><th>Canal</th><th>Estado</th><th /></tr></thead><tbody>{contacts.map((contact) => <tr key={contact.id}><td>{contact.service}</td><td>{contact.label}</td><td>{contact.status}</td><td><button onClick={() => setEditing(contact)}>Editar</button></td></tr>)}</tbody></table></>}</main>;
}
