import Link from"next/link";import{Contact,Footer,Header}from"../ui";
const pages:Record<string,[string,string,string,[string,string][]]>={
energia:["SERVICIO ELÉCTRICO","Energía para crecer juntos","Administrá tu suministro eléctrico y conocé los canales de guardia.",[["Nuevo suministro","Requisitos para una conexión domiciliaria, comercial o de obra."],["Cambio de titularidad","Actualizá el responsable del suministro."],["Falta de energía","Guardia 24 horas: 297 436-4961."],["Cortes programados","Consultá zonas y horarios estimados."]]],
"internet-telefonia":["CONECTIVIDAD","Internet y telefonía para estar conectados","Planes, asistencia técnica y gestiones de telecomunicaciones.",[["Planes de internet","Opciones para hogares, comercios e instituciones."],["Soporte técnico","Guardia: 297 464-1110."],["Telefonía fija","Alta, baja y cambio de titularidad."],["Configuración básica","Consejos para mejorar la señal Wi‑Fi."]]],
"fibra-optica":["FIBRA ÓPTICA","Conectividad de nueva generación","Conocé la red FTTH y solicitá una evaluación de cobertura.",[["Mayor velocidad","Conexión estable para múltiples dispositivos."],["Menor latencia","Mejor experiencia en videollamadas."],["Cobertura","Consultá disponibilidad técnica."],["Nueva conexión","Solicitá una evaluación."]]],
sepelio:["SERVICIO SOLIDARIO","Acompañamiento cuando más se necesita","Información y guardias del Servicio Solidario de Sepelios.",[["Acompañamiento","Orientación ante una necesidad."],["Grupo familiar","Mantené actualizada la nómina."],["Guardia","297 624-1614 / 297 624-1615."],["Requisitos","Consultá documentación y cobertura."]]],
"facturas-pagos":["FACTURACIÓN","Facturas y medios de pago","Alternativas para pagar tus servicios de forma segura.",[["Oficina Virtual","Consultá deuda y pagá online."],["Mercado Pago","Escaneá el código de la factura."],["Débito automático","Automatizá tus pagos."],["Red Link y Pago Fácil","Usá el código actualizado."]]],
tramites:["GESTIONES","Trámites de servicios","Altas, bajas, cambios de titularidad y otras solicitudes.",[["Nuevo suministro","Solicitá una conexión."],["Cambio de titularidad","Actualizá al responsable."],["Reconexión","Regularizá y pedí restitución."],["Factura digital","Recibí comprobantes por email."]]],
"estado-servicios":["INFORMACIÓN OPERATIVA","Estado de los servicios","Información oficial sobre cortes y mantenimientos.",[["Energía","Guardia: 297 436-4961."],["Internet","Soporte: 297 464-1110."],["Sepelio","Guardia: 297 624-1614."],["Comunicados","Consultá las noticias oficiales."]]],
institucional:["NUESTRA COOPERATIVA","COOPSAR, cerca de la comunidad","Servicios esenciales con compromiso cooperativo.",[["Comunidad","Arraigo y atención local."],["Energía","Distribución y mantenimiento."],["Conectividad","Internet, fibra y telefonía."],["Innovación","Nuevas herramientas digitales."]]],
contacto:["ATENCIÓN","Contactate con COOPSAR","Elegí el canal adecuado para tu consulta.",[["WhatsApp comercial","+54 9 2975 37-6656."],["Energía","297 436-4961."],["Internet","297 464-1110."],["Sepelio","297 624-1614 / 1615."]]]};
export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params,p=pages[slug];if(!p)return <main><Header/><section className="inner"><h1>Página no encontrada</h1><Link href="/">Volver</Link></section><Footer/></main>;return <main><Header/><section className="inner"><span className="tag">{p[0]}</span><h1>{p[1]}</h1><p>{p[2]}</p></section><section className="section cards">{p[3].map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</section><Contact/><Footer/></main>}
