"use client";

import { FormEvent, useEffect, useState } from "react";

type Plan = { id: string; slug: string; name: string; audience: "home" | "business" | "enterprise" | "all" | null; technology: string | null; speed_down_mbps: number | null; speed_up_mbps: number | null; price_amount: number | null; currency: string | null; status: "draft" | "published" | "archived"; sort_order: number };
const empty = (): Plan => ({ id: "", slug: "", name: "", audience: null, technology: null, speed_down_mbps: null, speed_up_mbps: null, price_amount: null, currency: null, status: "draft", sort_order: 0 });

export default function AdminInternetPlansPage() {
  const [plans, setPlans] = useState<Plan[]>([]); const [editing, setEditing] = useState<Plan | null>(null); const [message, setMessage] = useState("");
  const load = async () => { const response = await fetch("/api/admin/internet/plans", { cache: "no-store" }); const data = await response.json(); setPlans(data.plans || []); if (!response.ok) setMessage(data.error || "No pudimos cargar los planes."); };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); const price = String(form.get("price")).trim(); const audience = String(form.get("audience")); const payload = { id: editing.id || undefined, slug: String(form.get("slug")).trim(), name: String(form.get("name")).trim(), audience: audience || null, technology: String(form.get("technology")).trim() || null, speedDownMbps: Number(form.get("down")) || null, speedUpMbps: Number(form.get("up")) || null, priceAmount: price ? Number(price) : null, currency: price ? String(form.get("currency")) : null, installationPrice: null, installationNotes: null, description: null, conditions: null, benefits: [], status: String(form.get("status")), sortOrder: Number(form.get("sortOrder")) || 0 }; const response = await fetch("/api/admin/internet/plans", { method: editing.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) { setMessage(data.error || "No pudimos guardar el plan."); return; } setEditing(null); setMessage("Plan guardado."); await load(); }
  return <section className="admin-page"><header className="admin-page-header"><div><span className="eyebrow">Servicios</span><h1>Planes de Internet y Fibra</h1><p>Solo los planes publicados con fecha de publicación pueden mostrarse públicamente. Un precio vacío se muestra como “Consultar precio”.</p></div></header>{message && <p role="status" className="admin-message">{message}</p>}{editing ? <form className="news-editor" onSubmit={save}><label>Slug<input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" defaultValue={editing.slug} /></label><label>Nombre<input name="name" required defaultValue={editing.name} /></label><label>Segmento<select name="audience" defaultValue={editing.audience || ""}><option value="">Pendiente de confirmación</option><option value="home">Hogar</option><option value="business">Comercio</option><option value="enterprise">Empresa</option><option value="all">Todos</option></select></label><label>Tecnología<input name="technology" defaultValue={editing.technology || ""} /></label><label>Mbps bajada<input name="down" type="number" min="1" defaultValue={editing.speed_down_mbps || ""} /></label><label>Mbps subida<input name="up" type="number" min="1" defaultValue={editing.speed_up_mbps || ""} /></label><label>Precio oficial<input name="price" type="number" min="0" step="0.01" defaultValue={editing.price_amount || ""} /></label><label>Moneda<select name="currency" defaultValue={editing.currency || "ARS"}><option value="ARS">ARS</option><option value="USD">USD</option></select></label><label>Orden<input name="sortOrder" type="number" min="0" defaultValue={editing.sort_order} /></label><label>Estado<select name="status" defaultValue={editing.status}><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label><button className="primary">Guardar</button><button type="button" onClick={() => setEditing(null)}>Cancelar</button></form> : <><button className="primary" onClick={() => setEditing(empty())}>Nuevo plan</button><table><thead><tr><th>Nombre</th><th>Estado</th><th>Precio</th><th /></tr></thead><tbody>{plans.map((plan) => <tr key={plan.id}><td>{plan.name}</td><td>{plan.status}</td><td>{plan.price_amount === null ? "Consultar precio" : `${plan.currency} ${plan.price_amount}`}</td><td><button onClick={() => setEditing(plan)}>Editar</button></td></tr>)}</tbody></table></>}</section>;
}
