"use client";

import { FormEvent, useState } from "react";

type CoverageStatus = "available" | "nearby" | "planned" | "unavailable" | "unknown";
type Source = "manual_admin" | "csv_import" | "network_export" | "verified_internal";
type Row = { id: number; street_normalized: string; street_number: number; plan_name: string | null; technology: string; coverage_status: CoverageStatus; source: Source; verified_at: string | null };
const statuses: CoverageStatus[] = ["available", "nearby", "planned", "unavailable", "unknown"];
const sources: Source[] = ["manual_admin", "csv_import", "network_export", "verified_internal"];

export default function AdminCoveragePage() {
  const [street, setStreet] = useState(""); const [height, setHeight] = useState(""); const [rows, setRows] = useState<Row[]>([]); const [editing, setEditing] = useState<Row | null>(null); const [message, setMessage] = useState("");
  async function search(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/admin/coverage?street=${encodeURIComponent(street)}`, { cache: "no-store" }); const data = await response.json(); const matched = height ? (data.coverage || []).filter((row: Row) => row.street_number === Number(height)) : data.coverage || []; setRows(matched); setMessage(response.ok ? `${matched.length} registros` : data.error || "No pudimos cargar cobertura."); }
  async function save(event: FormEvent) { event.preventDefault(); if (!editing) return; const response = await fetch("/api/admin/coverage", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: editing.id, coverageStatus: editing.coverage_status, technology: editing.technology, source: editing.source, verifiedAt: editing.verified_at }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error || "No pudimos actualizar cobertura."); return; } setRows((current) => current.map((row) => row.id === data.coverage.id ? data.coverage : row)); setEditing(null); setMessage("Cobertura actualizada."); }
  return <section className="admin-page"><header className="admin-page-header"><div><span className="eyebrow">Servicios</span><h1>Cobertura de Internet/Fibra</h1><p>La cobertura domiciliaria es privada. Esta vista no muestra infraestructura de red. Para importaciones en lote usá el importador validado en entorno autorizado y primero ejecutá <code>-DryRun</code>.</p></div></header><form onSubmit={search}><label>Buscar calle normalizada o parcial<input value={street} onChange={(event) => setStreet(event.target.value)} /></label><label>Altura (opcional)<input inputMode="numeric" value={height} onChange={(event) => setHeight(event.target.value)} /></label><button className="primary">Buscar</button></form>{message && <p role="status">{message}</p>}<table><thead><tr><th>Calle</th><th>Altura</th><th>Estado</th><th>Tecnología</th><th>Fuente</th><th>Verificado</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.street_normalized}</td><td>{row.street_number}</td><td>{row.coverage_status}</td><td>{row.technology}</td><td>{row.source}</td><td>{row.verified_at ? new Date(row.verified_at).toLocaleDateString("es-AR") : "Sin fecha"}</td><td><button type="button" onClick={() => setEditing(row)}>Editar</button></td></tr>)}</tbody></table>{editing && <form onSubmit={save}><h2>Editar {editing.street_normalized} {editing.street_number}</h2><label>Estado<select value={editing.coverage_status} onChange={(event) => setEditing({ ...editing, coverage_status: event.target.value as CoverageStatus })}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><label>Tecnología<input value={editing.technology} onChange={(event) => setEditing({ ...editing, technology: event.target.value })} /></label><label>Fuente<select value={editing.source} onChange={(event) => setEditing({ ...editing, source: event.target.value as Source })}>{sources.map((source) => <option key={source}>{source}</option>)}</select></label><label>Fecha de verificación<input type="datetime-local" value={editing.verified_at ? editing.verified_at.slice(0, 16) : ""} onChange={(event) => setEditing({ ...editing, verified_at: event.target.value ? new Date(event.target.value).toISOString() : null })} /></label><button className="primary">Guardar cambios</button><button type="button" onClick={() => setEditing(null)}>Cancelar</button></form>}</section>;
}
