import type { Metadata } from "next";
import Image from "next/image";
import { Footer, Header } from "../ui";
import { getPublicContacts, getPublishedFuneralFaqs } from "../../lib/data/public-content";
import { getPublishedSitePage } from "../../lib/data/site-pages";
import { servicePages } from "../../lib/service-pages";
import { resolveFuneralGuard } from "../../lib/sepelio-presentation";
import { SepelioCoopiaAction } from "../components/sepelio-coopia-action";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Servicio de Sepelio | COOPSAR", description: "Orientación y acceso directo a la guardia del Servicio Solidario de Sepelios de COOPSAR." };

export default async function SepelioPage() {
  const [publishedPage, contacts, faqs] = await Promise.all([getPublishedSitePage("sepelio"), getPublicContacts("funeral"), getPublishedFuneralFaqs()]);
  const content = publishedPage ?? servicePages.sepelio;
  const guard = resolveFuneralGuard(contacts);
  return <><Header /><main className="sepelio-page">
    <section className="sepelio-hero" aria-labelledby="sepelio-title"><Image src="/images/sarmiento-community.png" alt="Comunidad de Sarmiento" fill priority sizes="100vw" /><div className="sepelio-hero-shade" /><div className="sepelio-hero-content"><p className="eyebrow">{content.eyebrow}</p><h1 id="sepelio-title">{content.title}</h1><p>{content.intro}</p><div className="sepelio-hero-actions"><a className="button sepelio-primary-action" href={guard.href}>Llamar a guardia <span>→</span></a><a className="button sepelio-secondary-action" href="#informacion">Consultar información</a></div></div><aside className="sepelio-emergency-card" aria-label="Atención urgente"><span className="sepelio-emergency-icon" aria-hidden="true">✦</span><p>Si necesitás el servicio ahora</p><strong>{guard.label}</strong><span>Canal directo de atención.</span></aside></section>
    <section id="informacion" className="sepelio-needs section-shell" aria-labelledby="sepelio-needs-title"><div className="section-heading"><p className="eyebrow">Servicio de sepelio</p><h2 id="sepelio-needs-title">¿Qué necesitás resolver?</h2><p>Elegí una opción para ir al canal adecuado.</p></div><div className="sepelio-needs-grid"><a className="sepelio-need sepelio-need-urgent" href={guard.href}><span className="sepelio-need-icon" aria-hidden="true">☎</span><strong>Necesito el servicio ahora</strong><small>Contactá a la guardia de sepelio.</small><b aria-hidden="true">→</b></a><SepelioCoopiaAction className="sepelio-need" prompt="Quiero consultar la cobertura del servicio de sepelio."><span className="sepelio-need-icon" aria-hidden="true">⌂</span>Consultar cobertura<span className="sepelio-need-description">COOPIA te orienta con información oficial.</span></SepelioCoopiaAction><SepelioCoopiaAction className="sepelio-need" prompt="Quiero consultar mi grupo familiar del servicio de sepelio."><span className="sepelio-need-icon" aria-hidden="true">◌</span>Mi grupo familiar<span className="sepelio-need-description">Pedí orientación sobre tu situación.</span></SepelioCoopiaAction><SepelioCoopiaAction className="sepelio-need" prompt="Tengo otra consulta sobre el servicio de sepelio."><span className="sepelio-need-icon" aria-hidden="true">?</span>Tengo otra consulta<span className="sepelio-need-description">Abrí COOPIA para encontrar el próximo paso.</span></SepelioCoopiaAction></div></section>
    <section className="sepelio-guidance section-shell" aria-labelledby="sepelio-guidance-title"><div><p className="eyebrow">Orientación</p><h2 id="sepelio-guidance-title">Acompañamiento claro, cuando lo necesitás.</h2></div><div><p>Para consultas sobre condiciones, grupo familiar o cobertura, podés iniciar una conversación con COOPIA. La atención urgente continúa por la guardia.</p><SepelioCoopiaAction className="text-link" prompt="Quiero información sobre el servicio de sepelio.">Abrir COOPIA</SepelioCoopiaAction></div></section>
    {faqs.length > 0 && <section className="sepelio-faq section-shell" aria-labelledby="sepelio-faq-title"><div className="section-heading"><p className="eyebrow">Preguntas frecuentes</p><h2 id="sepelio-faq-title">Información para acompañarte</h2></div><div>{faqs.map((faq) => <details key={`${faq.category}-${faq.question}`}><summary>{faq.question}<span aria-hidden="true">+</span></summary><p>{faq.answer}</p></details>)}</div></section>}
    <section className="sepelio-closing section-shell"><h2>Estamos para orientarte.</h2><p>Elegí el canal que mejor se adapte a lo que necesitás.</p><div><a className="button sepelio-primary-action" href={guard.href}>Llamar a guardia <span>→</span></a><SepelioCoopiaAction className="button sepelio-secondary-action" prompt="Necesito orientación sobre el servicio de sepelio.">Abrir COOPIA</SepelioCoopiaAction></div></section>
  </main><Footer /></>;
}
