-- Fase 4D / 2D: trazabilidad privada para contenido histórico curado.
-- Es aditiva: no publica, no elimina ni modifica contenido operativo existente.

alter table public.faqs
  add column if not exists import_key text;

create unique index if not exists faqs_import_key_unique_idx
  on public.faqs (import_key)
  where import_key is not null;

alter table public.public_contact_channels
  add column if not exists import_key text;

create unique index if not exists public_contact_channels_import_key_unique_idx
  on public.public_contact_channels (import_key)
  where import_key is not null;

alter table public.public_contact_channels
  drop constraint if exists public_contact_channels_channel_type_check;
alter table public.public_contact_channels
  add constraint public_contact_channels_channel_type_check
  check (channel_type in ('phone', 'guard_phone', 'whatsapp', 'email', 'url', 'address', 'hours'));

create table if not exists public.content_import_source_pages (
  id uuid primary key default gen_random_uuid(),
  source_system text not null default 'wordpress' check (source_system = 'wordpress'),
  source_slug text not null,
  source_url text not null check (source_url ~ '^https?://'),
  source_title text not null,
  source_post_date timestamptz,
  source_modified_at timestamptz,
  wordpress_status text,
  migration_decision text not null check (migration_decision in ('rewrite', 'merge', 'validate', 'archive', 'discard')),
  decision_reason text,
  raw_content_sha256 text not null check (raw_content_sha256 ~ '^[a-f0-9]{64}$'),
  imported_at timestamptz not null default now(),
  unique (source_system, source_slug)
);

create table if not exists public.content_import_provenance (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null check (entity_type in ('service', 'help_article', 'faq', 'internet_plan', 'contact_channel', 'coopia_knowledge')),
  entity_id uuid,
  entity_key text not null,
  source_system text not null default 'wordpress' check (source_system = 'wordpress'),
  source_slug text not null,
  source_url text not null check (source_url ~ '^https?://'),
  source_title text,
  source_modified_at timestamptz,
  migration_decision text not null check (migration_decision in ('rewrite', 'merge', 'validate', 'archive', 'discard')),
  raw_content_sha256 text not null check (raw_content_sha256 ~ '^[a-f0-9]{64}$'),
  import_outcome text not null default 'imported' check (import_outcome in ('imported', 'unchanged', 'skipped_conflict')),
  imported_at timestamptz not null default now(),
  unique (entity_type, entity_key, source_system, source_slug)
);

create table if not exists public.content_import_validation_queue (
  id uuid primary key default gen_random_uuid(),
  validation_key text not null unique check (validation_key ~ '^wordpress:validation:[a-f0-9]{64}$'),
  priority text not null check (priority in ('P0', 'P1', 'P2', 'P3')),
  item text not null,
  reason text not null,
  source_slugs jsonb not null check (jsonb_typeof(source_slugs) = 'array'),
  status text not null default 'open' check (status in ('open', 'resolved', 'dismissed')),
  imported_at timestamptz not null default now()
);

create index if not exists content_import_provenance_entity_idx
  on public.content_import_provenance (entity_type, entity_key);
create index if not exists content_import_provenance_source_idx
  on public.content_import_provenance (source_system, source_slug);

alter table public.content_import_source_pages enable row level security;
alter table public.content_import_provenance enable row level security;
alter table public.content_import_validation_queue enable row level security;
revoke all on public.content_import_source_pages, public.content_import_provenance, public.content_import_validation_queue from anon, authenticated;
grant all on public.content_import_source_pages, public.content_import_provenance, public.content_import_validation_queue to service_role;

comment on table public.content_import_source_pages is
  'Private evidence inventory from the historical WordPress migration; never a runtime source of truth.';
comment on table public.content_import_provenance is
  'Private entity-to-source audit metadata for historical WordPress imports; never public content.';
comment on table public.content_import_validation_queue is
  'Private human validation backlog generated by the historical WordPress migration.';
