-- Phase A: private, server-written journey analytics. No prompts or PII are stored.
create table if not exists public.user_journeys (
  id uuid primary key default gen_random_uuid(),
  journey_id text not null unique check (journey_id ~ '^JRN-[0-9]{4}-[A-F0-9]{8}$'),
  session_id text not null check (session_id ~ '^SES-[A-F0-9]{16}$'),
  user_id uuid null references auth.users(id) on delete set null,
  anonymous_id text null,
  started_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  completed_at timestamptz null,
  status text not null default 'active' check (status in ('active', 'completed', 'abandoned')),
  primary_intent text null,
  entry_page text null,
  final_result text null,
  resolved boolean not null default false,
  handoff boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.journey_events (
  id bigint generated by default as identity primary key,
  journey_id text not null references public.user_journeys(journey_id) on delete cascade,
  session_id text not null check (session_id ~ '^SES-[A-F0-9]{16}$'),
  event_type text not null,
  page text null,
  intent text null,
  service text null,
  agent text null,
  tool text null,
  action text null,
  result text null,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  duration_ms integer null check (duration_ms is null or duration_ms >= 0),
  created_at timestamptz not null default now()
);

alter table public.user_journeys enable row level security;
alter table public.journey_events enable row level security;

revoke all on public.user_journeys, public.journey_events from anon, authenticated;
revoke all on sequence public.journey_events_id_seq from anon, authenticated;
grant all on public.user_journeys, public.journey_events to service_role;
grant usage, select on sequence public.journey_events_id_seq to service_role;

create index if not exists user_journeys_session_idx on public.user_journeys (session_id, last_activity_at desc);
create index if not exists user_journeys_intent_idx on public.user_journeys (primary_intent, created_at desc);
create index if not exists journey_events_journey_idx on public.journey_events (journey_id, created_at);
create index if not exists journey_events_type_idx on public.journey_events (event_type, created_at desc);
create index if not exists journey_events_intent_idx on public.journey_events (intent, created_at desc);
