"use client";
import { FormEvent, useEffect, useState } from "react";
import type { SitePage } from "../../../../lib/site-pages";
type Item = SitePage["items"][number];
type ApiPage = { id: string; slug: SitePage["slug"]; eyebrow: string; title: string; intro: string; image_url: string | null; items: SitePage["items"]; status: "draft" | "published"; sort_order: number; created_at: string | null; updated_at: string | null };
export default function AdminPages() {
  const [pages, setPages] = useState<SitePage[]>([]); const [editing, setEditing] = useState<SitePage | null>(null); const [message, setMessage] = useState("");
  const load = async () => { const response = await fetch("/api/admin/site-pages", { cache: "no-store" }); const data = await response.json() as { error?: string; pages?: ApiPage[] }; if (!response.ok) setMessage(data.error || "No pudimos cargar las páginas."); else setPages((data.pages || []).map((page) => ({ id: page.id, slug: page.slug, eyebrow: page.eyebrow, title: page.title, intro: page.intro, imageUrl: page.image_url, items: page.items, status: page.status, sortOrder: page.sort_order, createdAt: page.created_at, updatedAt: page.updated_at }))); };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); const payload = { id: editing.id, slug: editing.slug, eyebrow: String(form.get("eyebrow")), title: String(form.get("title")), intro: String(form.get("intro")), imageUrl: String(form.get("imageUrl")).trim() || null, status: String(form.get("status")), sortOrder: Number(form.get("sortOrder")) || 0, items: editing.items }; const response = await fetch("/api/admin/site-pages", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || "No pudimos guardar la página."); setMessage(payload.status === "published" ? "Página publicada." : "Borrador guardado."); setEditing(null); await load(); }
  const updateItem = (index: number, key: keyof Item, value: string) => setEditing((page) => page ? { ...page, items: page.items.map((item, i) => i === index ? { ...item, [key]: value } : item) } : page);
  return <section className="admin-page"><header className="admin-page-header"><div><span className="eyebrow">Contenidos</span><h1>Páginas</h1><p>Los borradores no se muestran públicamente. Las páginas de sistema no pueden eliminarse.</p></div></header>{message && <p className="admin-message" role="status">{message}</p>}{editing ? <form className="admin-form" onSubmit={save}><label>Slug<input value={editing.slug} disabled /></label><label>Eyebrow<input name="eyebrow" required defaultValue={editing.eyebrow} /></label><label>Título<input name="title" required defaultValue={editing.title} /></label><label>Introducción<textarea name="intro" required defaultValue={editing.intro} /></label><label>Imagen (URL opcional)<input name="imageUrl" type="url" defaultValue={editing.imageUrl || ""} /></label><label>Orden<input name="sortOrder" type="number" min="0" defaultValue={editing.sortOrder} /></label><label>Estado<select name="status" defaultValue={editing.status}><option value="draft">Borrador</option><option value="published">Publicado</option></select></label><fieldset><legend>Cards / accesos</legend>{editing.items.map((item, index) => <div className="admin-item" key={`${item.title}-${index}`}><input aria-label="Título" value={item.title} onChange={(event) => updateItem(index, "title", event.target.value)} /><textarea aria-label="Texto" value={item.text} onChange={(event) => updateItem(index, "text", event.target.value)} /><input aria-label="Enlace" value={item.href} onChange={(event) => updateItem(index, "href", event.target.value)} /><button type="button" onClick={() => setEditing((page) => page ? { ...page, items: page.items.filter((_, i) => i !== index) } : page)}>Quitar</button></div>)}<button type="button" onClick={() => setEditing((page) => page ? { ...page, items: [...page.items, { title: "Nuevo acceso", text: "Descripción", href: "/" }] } : page)}>Agregar item</button></fieldset><div className="admin-form-actions"><button className="primary">Guardar</button><button type="button" onClick={() => setEditing(null)}>Cancelar</button>{editing.status === "published" && <a href={`/${editing.slug}`} target="_blank">Vista previa ↗</a>}</div></form> : <div className="admin-card admin-table-wrap"><table><thead><tr><th>Página</th><th>Slug</th><th>Estado</th><th>Última modificación</th><th /></tr></thead><tbody>{pages.map((page) => <tr key={page.id}><td>{page.title}</td><td>/{page.slug}</td><td><span className={`admin-status ${page.status}`}>{page.status === "published" ? "Publicado" : "Borrador"}</span></td><td>{page.updatedAt ? new Intl.DateTimeFormat("es-AR", { dateStyle: "short" }).format(new Date(page.updatedAt)) : "—"}</td><td><button onClick={() => setEditing(page)}>Editar</button></td></tr>)}</tbody></table>{pages.length === 0 && <p>El CMS se habilita al aplicar la migración en un entorno autorizado. El sitio conserva sus páginas actuales como fallback.</p>}</div>}</section>;
}
